config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :carts
  resources :listings
  resources :charges
  devise_for :users

  get '/home/contactus', to: 'home#contactus'
  get '/home/aboutus', to: 'home#aboutus'
  get '/home/termsandconditions', to: 'home#termsandconditions'
  root "listings#landing"
end

app/models/listing.rb
class Listing < ApplicationRecord
  resourcify
  before_destroy :not_referenced_by_any_order
  has_many_attached :image
  has_many :orders
  belongs_to :user

  def can_update?(user)
    return self.user == user || user.has_role?(:admin)
  end

  private

  def not_referenced_by_any_order
    unless orders.empty?
     errors.add(:base, "Orders present")
     throw :abort
    end
  end
  
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :landing]

  def index
     @listings = Listing.all.order("created_at desc")
  end

  def show
    @listing = Listing.find(params[:id])
  end

  def new
    @listing = current_user.listings.build
  end

  def create
    @listing = current_user.listings.build(listing_params)
    # render plain: listing.inspect
    # @listing.image.attach(params[:listing][:image])
    # @listing.user = current_user
    if @listing.save
      redirect_to listings_path, notice: 'Listing successfully created' 
    else
      render :new
    end
  end

  def update
    if @listing.update(listing_params)
      redirect_to @listing, notice: "Listing was successfully updated"
    else
      render :edit
    end
  end

  def edit
  end

  def destroy
    @listing.destroy
    redirect_to listings_path, notice: 'Listing successfully deleted'
end

end

private

def set_listing
  @listing = Listing.find(params[:id])
end

def listing_params
  params.required(:listing).permit( :title, :price, :description, :address, :city, :state, :country, :image)
end

app/helpers/listing_helper.rb
module ListingHelper

    def listing_author(listing)
        user_signed_in? && current_user.id == listing.user_id
    end
    
end

app/views/listings/_form.html.erb
<%# Form used to create and edit listings %>
<div class="form">
<%= form_with(model: listing, local: true) do |form| %>
 
<div class="block is info">
    <div class="field">
       <%= form.label :title, class: "label" %>
        <%= form.text_field :title, placeholder: "What is the name of your tek?", class: "input" %>
    </div>
    </div>

    

    <div class="field">
        <%= form.label :price, class: "label" %>
        <%= form.number_field :price, placeholder: "Set a price for your tek", class: "input" %>
    </div>



    <div class="field">
        <%= form.label :description, class: "label" %>
        <%= form.text_field :description, placeholder: "Describe your tek", class: "input" %>
    </div>

    <div class="field">
        <%= form.label :address, class: "label" %>
        <%= form.text_field :address, placeholder: "Input your mailing address", class: "input" %>
    </div>
<div class="columns">
<div class="column">
    <div class="field">
        <%= form.label :city, class: "label has-text-centered" %>
        <%= form.text_field :city, placeholder: "Mailing city", class: "input" %>
    </div>
    </div>
<div class="column">
    <div class="field">
        <%= form.label :state, class: "label has-text-centered" %>
        <%= form.text_field :state, placeholder: "Mailing state", class: "input" %>
    </div>
    </div>

<div class="column">
    <div class="field">
        <%= form.label :country, class: "label has-text-centered" %>
        <%= form.text_field :country, placeholder: "Mailing country", class: "input" %>
    </div>
    </div>
    </div>

    <div class="field">
        <%= form.label :image, class: "label" %>
        <%= form.file_field :image, class: "button is-primary" %>
    </div>

    <div class="form">
        <%= form.submit %>
    </div>

<% end %> 
</div>

app/views/listings/create.html.erb
<h1>Listing#create</h1>
<p>Find me in app/views/listing/create.html.erb</p>

app/views/listings/edit.html.erb
<h1 class="title has-text-centered"> Let's edit your tek!</h1><br />

<div class="pv4">
    <%= render 'form', listing: @listing %>
</div>

<%# When editing an image the form will display which will allow the user to change each field %>
<%# The fields will auto populate so that the user can see what is currently in each field %>
<%# All of the attached images for the listing will display at the bottom of the page %>

<% if listing_author(@listing) %>
<% if @listing.image.attached? %>
<% for img in @listing.image %>
        <%= image_tag img, width: 400 %>
      <% end %>
      
<% end %>
<% end %>

app/views/listings/index.html.erb
<div class="listing-index-grid pt4">

<%# If the listing has an image it will be displayed with a set width of 64 %>
  <% @listings.each do |listing| %>
    <div class="listing border-light">
      <div class="listing-thumb">
        <% if listing.image.attached? %>
          <% for img in listing.image %>
              <%= image_tag img, width: 64 %></th>
          <% end %>
        <% end %>
      </div>


    <div class="pa2 products">

<%# The listings index page will display listing image, title, price, description and country %>
      <h3 class="fw7 f4 title box has-text-centered has-text-justified"><%= link_to listing.title.capitalize, listing %></h3>
       <p class="f3 pb4"><%= number_to_currency(listing.price) %></p>
      <p class="content is-light"><strong>Description:</strong> <%= link_to listing.description, listing %></p>
      <p class="content"><strong>Country:</strong> <span class="tag is-warning"><%= link_to listing.country.capitalize, listing %></span></p>


      

<%# If any of the listings on the listing index page belong to the user currently signed in %>
<%# 'EDIT' and 'DELETE' buttons will show up on the listing, which the user will be able to use %>
<%# The user will be unable to see edit / delete buttons on listings which do not belong to them %>

      <% if listing_author(listing) %>
         <%= link_to 'Edit', edit_listing_path(listing), class: "button is-small is-primary" %>
         <%= link_to 'Delete', listing, method: :delete, data: { confirm: "Are you sure ?" }, class: "button is-small is-info" %>
      <% end %>
      
<%# The listing will also display the seller's username %>
      <p class="f5 has-text-left pt1">Seller: <strong><%= listing.user.username %></strong></p>

    </div>
  </div>
  <% end %>
</div>

app/views/listings/landing.html.erb


<figure class="image is-3by1 pt2">
<%# This is the main image on the landing page, it is also a link to the listings index page %>
  <%= link_to image_tag("4.png", :alt => "hero image"), listings_path %>
</figure>


                 <!-- CARD -->
                    <div class="block">
                        <div class="card">
                            <div class="card-content">
                                <p class="content pb4 has-text-justified">
  <%# This is a quick blurb introducing the user to the site and giving a quick set of instructions for its use %>
                                    Welcome to Tekmor. Your one stop shop for buying and selling all your electronic goods. Click on the logo on the center
                                    to go to the listings page and start shopping! You can reach the listings page at any time by clicking the Tekmor logo at the top lef of the screen.
                                    To read information about how to buy and sell on Tekmor, simply click the About us button below. Happy shopping.

                                </p>


<%# There are four large buttons on the landing page: Contact Us, Listings, About Us and Terms and Conditions %>
<%# Each button has a large image and text displaying what it does %>
<%# Both the image and the text are links that will take the user to the respective page %>
<div class="columns round pb5">
<div class="column circle">
                            <figure class="image is-128x128">
  
  <%= link_to image_tag("http://chittagongit.com/download/69785", class: "is-rounded"), home_contactus_path %>
<p class="content has-text-centered pt3 has-text-weight-semibold is-size-4"><%= link_to "Contact", home_contactus_path %></p>
</figure>
</div>

<div class="column circle">
<figure class="image is-128x128">
  <img class="is-rounded" src="https://cdn4.iconfinder.com/data/icons/e-commerce-icon-set/48/Cart-512.png">
  <p class="content has-text-centered pt3 has-text-weight-semibold is-size-4"><%= link_to "Listings", listings_path %></p>

</figure>
</div>

<div class="column circle">
<figure class="image is-128x128">
  <img class="is-rounded" src="https://png.pngtree.com/svg/20170622/17cd13a09d.png">
  <p class="content has-text-centered pt3 has-text-weight-semibold is-size-4"><%= link_to "About Us", home_aboutus_path %></p>

</figure>
</div>

<div class="column circle">
<figure class="image is-128x128">
  <img class="is-rounded" src="https://png.pngtree.com/svg/20160606/c681947a9c.svg">
  <p class="content has-text-centered pt3 has-text-weight-semibold is-size-4"><%= link_to "T & C's", home_termsandconditions_path %></p>

</figure>
</div>


<%# At the bottom of the page we have placeholder links to the website's twitter and facebook pages %>
                            </div>
                            <footer class="card-footer pt3">
                                <p class="card-footer-item">
                                    <span>
                                        <a href="">Twitter <i class="fa fa-twitter"></i></a>
                                    </span>
                                </p>
                                <p class="card-footer-item">
                                    <span>
                                        <a href="">Facebook <i class="fa fa-facebook"></i></a>
                                    </span>
                                </p>
                            </footer>
                        </div>
                    </div>
                    


app/views/listings/new.html.erb
<%# When creating a listing the listing form will be generated for the user to fill in %>
<%# The top of the page will prompt the user what to do and will prompt them by using their username %>

<h1 class="title has-text-centered">Hi <%= @current_user.username.capitalize %>. Let's sell your tek!</h1><br />

<div class="pv4">
<%= render 'form', listing: @listing %>
</div>

app/views/listings/show.html.erb
<%# This page displays after the user clicks on a listing %>
<%# The page gives a more detailed description of the selected listing %>

<% content_for :body_class, 'bg-light' %>

<section class="section listing-show">
  <div class="columns">
    <div class="column is-8">
      <h1 class="title is-2"><%= @listing.title %></h1>

<%# If the image has one or more images attached they will all be displayed %>
        <% if @listing.image.attached? %>
            <% for img in @listing.image %>
                <%= image_tag img %></th>
            <% end %>
        <% end %>
      

      <div class="content pa4 mt3 bg-white border-radius-3">

      <h3 class="subtitle is-4">Description:</h3>
      
      <%= @listing.description %>


     
        
    </div>
    </div>
    <div class="column is-3 is-offset-1">
      <div class="bg-white pa4 border-radius-3">
        <h4 class="title is-5 has-text-centered"><%= number_to_currency(@listing.price) %></h4>
        <p class="has-text-centered mb4">Sold by <%= @listing.user.email %></p>
        <%# This button will allow the user to add the item to the cart, the user will then be redirected to the show cart page %>
        <%= button_to 'Add to cart', orders_path(listing_id: @listing), class: 'button is-warning add-to-cart' %>
      </div>
    </div>
  </div>

<%# If the listing belongs to the user who is currently signed in the page will render 'EDIT' and 'DELETE' buttons %>
<%# The user will be able to use these buttons to edit or delete the listing %>
<%# If the listing does not belong to the user these buttons will not render %>
  <% if listing_author(@listing) %>
    <%= link_to 'Edit', edit_listing_path(@listing), class: "button is-small is-primary" %>
  <% end %>


  <% if listing_author(@listing) %>
         <%= link_to 'Delete', @listing, method: :delete, data: { confirm: "Are you sure ?" }, class: "button is-small is-info" %>
      <% end %>

      </section>