config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :carts
  resources :listings
  resources :charges
  devise_for :users

  get '/home/contactus', to: 'home#contactus'
  get '/home/aboutus', to: 'home#aboutus'
  get '/home/termsandconditions', to: 'home#termsandconditions'
  root "listings#landing"
end

app/models/listing.rb
class Listing < ApplicationRecord
  resourcify
  before_destroy :not_referenced_by_any_order
  has_many_attached :image
  has_many :orders
  belongs_to :user

  def can_update?(user)
    return self.user == user || user.has_role?(:admin)
  end

  private

  def not_referenced_by_any_order
    unless orders.empty?
     errors.add(:base, "Orders present")
     throw :abort
    end
  end
  
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :landing]

  def index
     @listings = Listing.all.order("created_at desc")
  end

  def show
    @listing = Listing.find(params[:id])
  end

  def new
    @listing = current_user.listings.build
  end

  def create
    @listing = current_user.listings.build(listing_params)
    # render plain: listing.inspect
    # @listing.image.attach(params[:listing][:image])
    # @listing.user = current_user
    if @listing.save
      redirect_to listings_path, notice: 'Listing successfully created' 
    else
      render :new
    end
  end

  def update
    if @listing.update(listing_params)
      redirect_to @listing, notice: "Listing was successfully updated"
    else
      render :edit
    end
  end

  def edit
  end

  def destroy
    @listing.destroy
    redirect_to listings_path, notice: 'Listing successfully deleted'
end

end

private

def set_listing
  @listing = Listing.find(params[:id])
end

def listing_params
  params.required(:listing).permit( :title, :price, :description, :address, :city, :state, :country, :image)
end

app/helpers/listing_helper.rb
module ListingHelper

    def listing_author(listing)
        user_signed_in? && current_user.id == listing.user_id
    end
    
end

app/views/listing/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>

    <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div class="field">
        <%= form.label :price %>
        <%= form.text_field :price %>
    </div>

    <div class="field">
        <%= form.label :description %>
        <%= form.text_field :description %>
    </div>

    <div class="field">
        <%= form.label :address %>
        <%= form.text_field :address %>
    </div>

    <div class="field">
        <%= form.label :city %>
        <%= form.text_field :city %>
    </div>

    <div class="field">
        <%= form.label :state %>
        <%= form.text_field :state %>
    </div>

    <div class="field">
        <%= form.label :country %>
        <%= form.text_field :country %>
    </div>

    <div class="actions">
        <%= form.submit %>
    </div>

<% end %>

app/views/listing/new.html.erb
<h1>Listing#new</h1>
<p>Find me in app/views/listing/new.html.erb</p>

<%= render 'form', listing: @listing %>

<%= link_to  "Back", listing_index_path, class: 'btn btn-info' %>