config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :carts
  resources :listings
  resources :charges
  devise_for :users

  get '/home/contactus', to: 'home#contactus'
  get '/home/aboutus', to: 'home#aboutus'
  get '/home/termsandconditions', to: 'home#termsandconditions'
  root "listings#landing"
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :orders, dependent: :destroy

    def add_listing(listing)
        current_item = orders.find_by(listing_id: listing.id)

        if current_item
            current_item.increment(:quantity)
        else
            current_item = orders.build(listing_id: listing.id)
        end
            current_item
    end

    def total_price
        orders.to_a.sum { |item| item.total_price }
    end
    
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
    before_action :set_cart, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!
  
    def index
      @carts = Cart.all
    end
  
    def new
      @order = Order.new
      
    end
  
    def show
      @listings = Listing.all.order("created_at desc")
      # the_listing_id = params[:id]
      # @listing = Cart.find(the_listing_id)
      # Stripe.api_key = 'sk_test_5VriwPJF8EScOW0VlkIW36p200X2SvMzbP'
  
      # line_items = @cart.listings.map { |listing|
      #   {
      #     name: listings.title,
      #     amount: listings.price
      #   }
      # }
  
      # @stripe_checkout_session =  Stripe::Checkout::Session.create(
      #   payment_method_types: ['card'],
      #   line_items: [{
      #     name: @listing.title,
      #     description: @listing.description,
      #     amount: (@listing.price * 100).to_i,
      #     currency: 'aud',
      #     quantity: '1'
      #   }],
      #   success_url: 'http://localhost3000/success',
      #   cancel_url: 'http://localhost3000/cancel',
      # )
    end
  
    def edit
    end
  
    def create
      @cart = Cart.new(cart_params)
  
      if @cart.save
        redirect_to @cart, notice: "Cart was successfully created"
  
      else
        render :new
      end
  
    end
  
    def update
      if @cart.update(cart_params)
        redirect_to @cart, notice: "Cart was successfully updated"
      else
        render :edit
      end
    end
  
  
    def destroy
      @cart.destroy if @cart.id == session[:cart_id]
      session[:cart_id] = nil
      redirect_to listings_path, notice: "Cart was successfully deleted"
    end
  
  
  private
  
    def set_cart
      @cart = Cart.find(params[:id])
    end
  
    def cart_params
      params.fetch(:cart, {})
    end
  
    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to root_path, notice: "That cart doesn't exist"
    end
  
  end
  

app/helpers/carts_helper.rb
module CartsHelper
    def cart_count_over_one
        if total_cart_items > 0
          return "<span class='tag is-dark'>#{total_cart_items}</span>".html_safe
        end
    end
    
    def total_cart_items
         total = @cart.orders.map { |item| item.quantity }.sum
         return total if total > 0
    end
end

app/views/carts/create.html.erb
<h1>Carts#create</h1>
<p>Find me in app/views/carts/create.html.erb</p>

app/views/carts/destroy.html.erb
<h1>Carts#destroy</h1>
<p>Find me in app/views/carts/destroy.html.erb</p>

app/views/carts/edit.html.erb
<h1>Carts#edit</h1>
<p>Find me in app/views/carts/edit.html.erb</p>

app/views/carts/index.html.erb
Untitled 
<p id="notice"><%= notice %></p>
<h1>Carts</h1>
<table>
 <thead>
  <tr>
   <th colspan="3"></th>
  </tr>
 </thead>
 <tbody>
  <% @carts.each do |cart| %>
   <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
   </tr>
  <% end %>
 </tbody>
</table>
<br>
<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>



<%= render 'listings/form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<%# This page shows when the user adds an item to their cart %>
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>

<div class="keep-shopping pv1 mt4 has-text-right">

<%# A user is able to click the keep shopping link to back to the listings index, their item(s) will remain in the cart %>
  <%= link_to 'Keep Shopping', listings_path, class: 'button is-warning' %>
</div>
<hr />
<section class="section">

<%# Itereate through cart items which have images and render all images as thumbnails with the item information %>
<%# Else if the item does not have an image just render item information %>
<% @cart.orders.each do |x| %>
  
    <% if x.listing.image.attached? %>
      <% for img in x.listing.image %>
        <%= image_tag img, width: 64 %>
      <% end %>
      <%= render x %>
    <% else %>
    <%= render x %>
  <% end %>
<% end %>


  <div class="columns">
    <div class="column">
<%# Completely remove all items from the cart %>
<%# The user will be asked if they are sure to prevent them from accidently clicking the button and losing their cart %>  
      <%= button_to 'Empty Cart', @cart, method: :delete, data: { confirm: "Are you sure? " }, class: "button is-danger" %>
    </div>
    
    <div class="column total has-text-right">
      <h4 class="title is-4">
<%# Display total price of all cart items %>      
        <span class="f5 has-text-grey">Total:</span> <%= number_to_currency(@cart.total_price) %>
      </h4>
    </div>
  </div>
</section>

<%# Code from Stripe documentation to generate Stripe form %>

<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
<%# Charge the user the total amount for the items in their cart %>
    <label class="amount">
      <span>Amount: <%= number_to_currency(@cart.total_price) %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Payment details"
          data-amount="<%= number_to_currency(@cart.total_price) %>"
          data-locale="auto"></script>
<% end %>

app/views/carts/update.html.erb
<h1>Carts#update</h1>
<p>Find me in app/views/carts/update.html.erb</p>